version: '3.8'
services:
   minio:
    image: quay.io/minio/minio
    volumes:
      - ~/minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: bogish
      MINIO_ROOT_PASSWORD: 0305s31992
    command: server --console-address ":9001" /data
