version: '3.8'
services:
  database:
    image: postgres:12-alpine
    volumes:
      - ~/pg_data_2:/var/lib/postgresql/data
      - ./log:/root/log:delegated

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: GowishApi1
      POSTGRES_DB: gowish_api_development
      PSQL_HISTFILE: /root/log/.psql_history

    command: postgres -c 'max_connections=200'

  minio:
    image: quay.io/minio/minio
    volumes:
      - ~/minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data

  app: &app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      PORT: 3000
      RAILS_ENV: development
      PG_HOST: database
      PG_USER: postgres
      PG_PASSWORD: GowishApi1
    entrypoint: ./docker/app/entrypoint.sh
    command: bundle exec rails s -b 0.0.0.0
    depends_on:
      - database
      - minio
    ports:
      - 3000:3000
    volumes:
      - ./:/app:cached
      - app_bundle:/usr/local/bundle:delegated

  bot:
    <<: *app
    entrypoint: ./docker/bot/entrypoint.sh
    ports: []
    depends_on:
      - app
      - database
    # restart: always
    command: ./bin/bot

volumes:
  app_bundle:
