version: '3.8'
services:
  database:
    image: postgres:12-alpine
    volumes:
      - ~/pg_data_2:/var/lib/postgresql/data
      - ./log:/root/log:delegated

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: GowishApi1
      POSTGRES_DB: gowish_api_production
      PSQL_HISTFILE: /root/log/.psql_history

    command: postgres -c 'max_connections=200'

  app: &app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      RAILS_ENV: production
      PG_HOST: database
      PG_USER: postgres
      PG_PASSWORD: GowishApi1

    entrypoint: ./docker/app/entrypoint.sh

    command: bundle exec rails s

    depends_on:
      - database

    ports:
      - 3000:3000

    volumes:
      - ./:/app:cached
      - app_bundle:/usr/local/bundle:delegated

  bot:
    <<: *app

    entrypoint: ./docker/bot/entrypoint.sh

    ports: []

    depends_on:
      - app
      - database

    restart: always

    command: ./bin/bot

volumes:
  app_bundle:
